import type { AgentTask, AgentResult, WorkflowLog } from "@/lib/agents/agent-types";

export const MOCK_TASKS: AgentTask[] = [
  {
    id: "task-001",
    source: "user",
    userMessage: "Jarvis, ich habe eine neue Kundenanfrage von einem KMU aus Wien. Wer soll das übernehmen?",
    intent: "customer_inquiry",
    assignedAgents: ["nova", "vega", "lina"],
    status: "in_progress",
    priority: "high",
    resultSummary: "Nova hat klassifiziert: qualifizierter Lead. Vega bereitet Sales-Strategie vor. Lina formuliert Antwortmail.",
    requiresApproval: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "task-002",
    source: "user",
    userMessage: "Jarvis, erstelle mir eine Angebotsstruktur für einen KI-Chatbot für einen Onlineshop.",
    intent: "create_offer",
    assignedAgents: ["vega", "lina", "kira", "nox"],
    status: "awaiting_approval",
    priority: "high",
    resultSummary: "Vega: 3 Pakete (1.500–8.500 EUR). Lina: Angebotstext fertig. Kira: 1 Compliance-Hinweis. Nox: QA OK.",
    requiresApproval: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "task-003",
    source: "user",
    userMessage: "Jarvis, plane mir Content für nächste Woche über KI-Automatisierung.",
    intent: "plan_content",
    assignedAgents: ["elara", "orion", "lina", "vega", "kira", "nox"],
    status: "completed",
    priority: "medium",
    resultSummary: "Contentplan mit 5 Beiträgen erstellt. Captions fertig. Kreativbriefing übergeben. Compliance OK.",
    requiresApproval: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "task-004",
    source: "user",
    userMessage: "Jarvis, ich habe ein technisches Problem mit unserem Webhook zur CRM-Anbindung.",
    intent: "technical_issue",
    assignedAgents: ["soren", "atlas", "nox", "forge"],
    status: "in_progress",
    priority: "urgent",
    resultSummary: "Soren: Intake Ticket erstellt. Atlas: 3 mögliche Ursachen. Nox: API-Key-Prüfung läuft.",
    requiresApproval: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: "task-005",
    source: "user",
    userMessage: "Jarvis, prüfe unsere Landing Page auf Security und Compliance vor dem Go-Live.",
    intent: "security_qa_check",
    assignedAgents: ["nox", "kira", "atlas", "soren"],
    status: "completed",
    priority: "high",
    resultSummary: "Nox: 1 kritisches Finding (RLS). Kira: 2 DSGVO-Hinweise. Atlas: Architektur OK. Go-Live nach RLS-Fix.",
    requiresApproval: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
  },
  {
    id: "task-006",
    source: "user",
    userMessage: "Jarvis, bereite ein Developer-Briefing für Claude Code vor — wir bauen eine neue API-Integration.",
    intent: "developer_briefing",
    assignedAgents: ["forge", "soren", "atlas", "nox"],
    status: "completed",
    priority: "medium",
    resultSummary: "Forge: vollständiges Dev-Briefing erstellt. Soren: Setup validiert. Atlas: Architekturkontext bereit. Nox: grünes Licht.",
    requiresApproval: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 47).toISOString(),
  },
];

export const MOCK_LOGS: Record<string, WorkflowLog[]> = {
  "task-001": [
    { id: "l1", taskId: "task-001", eventType: "task_created", message: "Aufgabe erstellt: customer_inquiry", createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString() },
    { id: "l2", taskId: "task-001", eventType: "agent_activated", agentId: "nova", message: "Nova wurde aktiviert", createdAt: new Date(Date.now() - 1000 * 60 * 17).toISOString() },
    { id: "l3", taskId: "task-001", eventType: "agent_result", agentId: "nova", message: "Nova: Qualifizierter Lead erkannt — KMU Wien, KI-Automatisierung", createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString() },
    { id: "l4", taskId: "task-001", eventType: "agent_activated", agentId: "vega", message: "Vega wurde aktiviert", createdAt: new Date(Date.now() - 1000 * 60 * 14).toISOString() },
    { id: "l5", taskId: "task-001", eventType: "agent_activated", agentId: "lina", message: "Lina wurde aktiviert", createdAt: new Date(Date.now() - 1000 * 60 * 14).toISOString() },
    { id: "l6", taskId: "task-001", eventType: "agent_result", agentId: "vega", message: "Vega: Sales-Einschätzung — Abschlusswahrscheinlichkeit 65%", createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString() },
    { id: "l7", taskId: "task-001", eventType: "agent_result", agentId: "lina", message: "Lina: Antwortmail-Entwurf fertiggestellt — wartet auf Freigabe", createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString() },
  ],
  "task-002": [
    { id: "l8", taskId: "task-002", eventType: "task_created", message: "Aufgabe erstellt: create_offer", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
    { id: "l9", taskId: "task-002", eventType: "agent_activated", agentId: "vega", message: "Vega wurde aktiviert", createdAt: new Date(Date.now() - 1000 * 60 * 118).toISOString() },
    { id: "l10", taskId: "task-002", eventType: "agent_result", agentId: "vega", message: "Vega: 3 Angebotsstrukturen erstellt (S/M/L)", createdAt: new Date(Date.now() - 1000 * 60 * 100).toISOString() },
    { id: "l11", taskId: "task-002", eventType: "agent_result", agentId: "lina", message: "Lina: Angebotstext formuliert", createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString() },
    { id: "l12", taskId: "task-002", eventType: "agent_result", agentId: "kira", message: "Kira: 1 Compliance-Hinweis — AGB-Verweis fehlt", createdAt: new Date(Date.now() - 1000 * 60 * 80).toISOString() },
    { id: "l13", taskId: "task-002", eventType: "agent_result", agentId: "nox", message: "Nox: QA-Check bestanden — kein kritisches Finding", createdAt: new Date(Date.now() - 1000 * 60 * 70).toISOString() },
    { id: "l14", taskId: "task-002", eventType: "approval_requested", message: "Freigabe angefordert: Angebot vor Versand freigeben", createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString() },
  ],
  "task-004": [
    { id: "l15", taskId: "task-004", eventType: "task_created", message: "URGENT: Technisches Problem gemeldet", createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString() },
    { id: "l16", taskId: "task-004", eventType: "agent_activated", agentId: "soren", message: "Soren wurde aktiviert — Prio 1", createdAt: new Date(Date.now() - 1000 * 60 * 7).toISOString() },
    { id: "l17", taskId: "task-004", eventType: "agent_result", agentId: "soren", message: "Soren: Intake Ticket erstellt — Webhook-Fehler CRM", createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString() },
    { id: "l18", taskId: "task-004", eventType: "agent_activated", agentId: "atlas", message: "Atlas analysiert Ursachen", createdAt: new Date(Date.now() - 1000 * 60 * 4).toISOString() },
    { id: "l19", taskId: "task-004", eventType: "agent_activated", agentId: "nox", message: "Nox prüft API-Key-Schutz", createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString() },
  ],
};

export const MOCK_TASK_RESULTS: Record<string, AgentResult[]> = {
  "task-002": [
    {
      id: "r1", taskId: "task-002", agentId: "vega", status: "done",
      summary: "3 Angebotsstrukturen erstellt: S (1.500–2.500 EUR) · M (3.500–5.500 EUR) · L (6.500–8.500 EUR)",
      details: "Paketlogik mit klarer Leistungsabgrenzung. Mittleres Paket als Anker positioniert.",
      suggestedActions: ["Paket mit Kunden abstimmen", "Angebotstext finalisieren"],
      risks: [],
      createdAt: new Date(Date.now() - 1000 * 60 * 100).toISOString(),
    },
    {
      id: "r2", taskId: "task-002", agentId: "kira", status: "done",
      summary: "Compliance: AGB-Verweis fehlt — Gelbes Risiko",
      details: "Impressum vorhanden. USt.-Hinweis (20%) fehlt. AGB nicht referenziert.",
      suggestedActions: ["AGB-Verweis ergänzen", "USt.-Ausweis prüfen"],
      risks: ["Fehlender AGB-Hinweis"],
      createdAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    },
  ],
};
